name: CTest

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependecies
      run: |
        sudo apt update
        sudo apt install cmake wget g++ -y
        
    - name: Install GTest
      run: |
        sudo apt-get install libgtest-dev -y
        cd /usr/src/gtest
        sudo cmake CMakeLists.txt
        sudo make
        cd lib/
        sudo cp *.a /usr/lib

    - name: Install ByteUtils library
      run: |
        wget https://github.com/oprisor-adrian/byte-utilities/archive/v1.1-alpha.tar.gz
        sudo tar -xzf v1.1-alpha.tar.gz
        cd byte-utilities-1.1-alpha/
        sudo cmake -S . -B build/
        cd build/
        sudo make install

    - name: Create Build Directory
      run: mkdir build

    - name: Configure CMake
      run: cmake -B build

    - name: Build
      run: cmake --build build

    - name: Test
      run: ctest --test-dir build
