name: CTest

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependecies
      run: |
        sudo apt update
        sudo apt install cmake git g++ -y
        
    - name: Install GTest
      run: |
        sudo apt-get install libgtest-dev -y
        cd /usr/src/gtest
        sudo cmake CMakeLists.txt
        sudo make
        cd lib/
        sudo cp *.a /usr/lib

    - name: Install byte_utils library
      run: |
        git submodule update --init
        cd lib/byte_utils
        sudo mkdir build
        sudo cmake -B build
        cd build/
        sudo make install

    - name: Create Build Directory
      run: mkdir build

    - name: Configure CMake
      run: cmake -B build

    - name: Build
      run: cmake --build build

    - name: Test
      run: ctest --test-dir build
